# Generated by Django 2.2.14 on 2020-08-02 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(max_length=5)),
                ('zone_temperature', models.IntegerField(default=20)),
                ('zone_light_color', models.CharField(default='00FF00', max_length=6)),
            ],
        ),
    ]
