# Generated by Django 2.2.14 on 2020-08-02 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usman', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='description',
            field=models.CharField(default='N/A', max_length=11),
        ),
        migrations.AddField(
            model_name='zone',
            name='floor',
            field=models.IntegerField(default=1),
        ),
    ]
