# Generated by Django 2.2.14 on 2020-08-09 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usman', '0002_auto_20200802_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zone',
            old_name='zone_temperature',
            new_name='temperature_set',
        ),
        migrations.AddField(
            model_name='zone',
            name='temperature_actual',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
    ]
