# Generated by Django 2.2.14 on 2020-08-09 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usman', '0003_auto_20200808_1810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zone',
            old_name='zone_light_color',
            new_name='light_color',
        ),
    ]
